export const PRODUCTS_FETCHING = "PRODUCTS_FETCHING"
export const PRODUCTS_FETCHED = "PRODUCTS_FETCHED"
export const PRODUCTS_LOADER = "PRODUCTS_LOADER"
export const PRODUCTS_ERROR_STATUS = "PRODUCTS_ERROR_STATUS"